[workspace]
# Update the workspace name accordingly
name = "ros_docker_ws"
authors = ["Erik Holum <erik.holum@nasa.gov>"]
channels = [
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/robostack-jazzy",
]
platforms = ["linux-aarch64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[activation]
# Sources the workspace install, if present
scripts = ["scripts/entrypoint_pixi.sh"]

[activation.env]
LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LIBRARY_PATH}"
LD_LIBRARY_PATH = "${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}"
LDFLAGS = "-L${CONDA_PREFIX}/lib -Wl,-rpath,${CONDA_PREFIX}/lib -fuse-ld=mold"
COLCON_DEFAULT_OUTPUT_STYLE = "catkin_tools"
COLCON_DEFAULTS_FILE = "${PIXI_PROJECT_ROOT}/config/colcon-defaults.yaml"
RCUTILS_COLORIZED_OUTPUT = "1"

[tasks]
# Setup tasks
setup-colcon = { cmd = """
colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
colcon mixin update default
""" }

# Build tasks
build = "colcon build"
test = "colcon test"
test-result = "colcon test-result --verbose"
clean = "rm -rf build/* install/* log/*"

[dependencies]
python = ">=3.11,<3.13"
cmake = ">=4.1.2,<5"
ccache = ">=4.13.1,<5"
ninja = ">=1.13.1,<2"
mold = ">=2.40.4,<3"
colcon-common-extensions = ">=0.3.0,<0.4"
colcon-mixin = ">=0.2.3,<0.3"
pip = "*"

# Not necessary for building, but for tests/running in isolated environments
ros-jazzy-ros-base = "*"

[dev]
# Add path dependencies to any sources in the workspace, for example:
# ros-jazzy-clr-deploy = { path = "./src/chonkur_l_raile/clr_deploy/package.xml" }
