<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>togo_gz</name>
  <version>0.0.0</version>
  <description>Gazebo sim package for Clearpath Husky known as Togo</description>
  <maintainer email="emily.j.sheetz@nasa.gov">Emily Sheetz</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>clearpath_platform_description</depend>

  <depend>rclcpp</depend>
  <depend>tf2_sensor_msgs</depend>
  <depend>tf2_geometry_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros2_control</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>
  <!-- gazebo dependencies -->
  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <!-- togo dependencies -->
  <exec_depend>togo_description</exec_depend>
  <exec_depend>togo_deploy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
